const data = {
    users: [

        {
            name: 'md Milon Mia',
            email: 'mdmilonmiah200@gmail.com',
            password: "Milon2005",
            phone: '01782671468',
            address: 'sadulapur',
            isAdmin: true,
            isVerified: true,
        },
        {
            name: 'md Anamul Mia',
            email: 'mdanamulmiah2005@gmail.com',
            password: "Milon2005",
            phone: '0174003333',
            address: 'sadulapur, gaibandha'
        },
        {
            name: 'md Akash Mia',
            email: 'mdakashmiah2005@gmail.com',
            password: "Milon2005",
            phone: '0178489484',
            address: 'sadulapur, lakmipur'
        },
    ],
    products: [
        {
            "id": 1,
            "name": "Premium Slim Fit Cotton Shirt",
            "category": "shirt",
            "price": 1450,
            "original_price": 1800,
            "currency": "BDT",
            "sizes": ["S", "M", "L", "XL"],
            "colors": ["White", "Sky Blue", "Navy Blue"],
            "stock": 45,
            "rating": 4.7,
            "image_url": "https://example.com",
            "description": "100% premium cotton slim fit formal shirt for everyday office wear."
        },
        {
            "id": 2,
            "name": "Traditional Semi-Long Cotton Panjabi",
            "category": "panjabi",
            "price": 2200,
            "original_price": 2200,
            "currency": "BDT",
            "sizes": ["38", "40", "42", "44"],
            "colors": ["Maroon", "Black", "White"],
            "stock": 20,
            "rating": 4.5,
            "image_url": "https://example.com",
            "description": "Comfortable cotton semi-long panjabi with elegant embroidery work on the collar."
        },
        {
            "id": 3,
            "name": "Stretchable Slim Fit Denim Jeans",
            "category": "pant",
            "price": 1850,
            "original_price": 2400,
            "currency": "BDT",
            "sizes": ["30", "32", "34", "36"],
            "colors": ["Deep Blue", "Light Wash"],
            "stock": 60,
            "rating": 4.8,
            "image_url": "https://example.com",
            "description": "Durable and stretchable denim pant for ultimate daily comfort."
        },
        {
            "id": 4,
            "name": "Heavyweight Cotton Oversized T-Shirt",
            "category": "t-shirt",
            "price": 650,
            "original_price": 850,
            "currency": "BDT",
            "sizes": ["M", "L", "XL"],
            "colors": ["Black", "Beige", "Olive Green"],
            "stock": 110,
            "rating": 4.6,
            "image_url": "https://example.com",
            "description": "260 GSM drop-shoulder oversized t-shirt made with breathable cotton fabric."
        },
        {
            "id": 5,
            "name": "Casual Linen Full Sleeve Shirt",
            "category": "shirt",
            "price": 1600,
            "original_price": 1950,
            "currency": "BDT",
            "sizes": ["M", "L", "XL"],
            "colors": ["Olive", "Khaki", "White"],
            "stock": 35,
            "rating": 4.4,
            "image_url": "https://example.com",
            "description": "Lightweight linen blend shirt perfect for summer and casual outings."
        },
        {
            "id": 6,
            "name": "Luxury Georgette Kabli Set",
            "category": "panjabi",
            "price": 3800,
            "original_price": 4500,
            "currency": "BDT",
            "sizes": ["40", "42", "44"],
            "colors": ["Jet Black", "Navy Blue"],
            "stock": 15,
            "rating": 4.9,
            "image_url": "https://example.com",
            "description": "Premium Kabli set with matching pajama, designed for festivals and wedding events."
        },
        {
            "id": 7,
            "name": "Slim Fit Cotton Chino Pant",
            "category": "pant",
            "price": 1250,
            "original_price": 1600,
            "currency": "BDT",
            "sizes": ["28", "30", "32", "34", "36"],
            "colors": ["Beige", "Black", "Grey"],
            "stock": 50,
            "rating": 4.3,
            "image_url": "https://example.com",
            "description": "Versatile smart-casual chinos that pair perfectly with shirts or t-shirts."
        },
        {
            "id": 8,
            "name": "Minimalist Solid Color Polo T-Shirt",
            "category": "t-shirt",
            "price": 800,
            "original_price": 1100,
            "currency": "BDT",
            "sizes": ["S", "M", "L", "XL"],
            "colors": ["Red", "Royal Blue", "Charcoal"],
            "stock": 85,
            "rating": 4.5,
            "image_url": "https://example.com",
            "description": "Classic pique cotton polo shirt with a clean minimalist design."
        },
        {
            "id": 9,
            "name": "Cuban Collar Printed Rayon Shirt",
            "category": "shirt",
            "price": 1150,
            "original_price": 1500,
            "currency": "BDT",
            "sizes": ["M", "L", "XL"],
            "colors": ["Floral Print", "Abstract Black"],
            "stock": 25,
            "rating": 4.2,
            "image_url": "https://example.com",
            "description": "Trendy relaxed-fit printed resort shirt made of soft rayon fabric."
        },
        {
            "id": 10,
            "name": "Digital Printed Viscose Panjabi",
            "category": "panjabi",
            "price": 1950,
            "original_price": 2500,
            "currency": "BDT",
            "sizes": ["38", "40", "42", "44"],
            "colors": ["Multicolor Blue", "Multicolor Maroon"],
            "stock": 40,
            "rating": 4.6,
            "image_url": "https://example.com",
            "description": "Modern vibrant digital prints on premium soft viscose fabric for a stylish look."
        },
        {
            "id": 11,
            "name": "Relaxed Fit Cargo Pant",
            "category": "pant",
            "price": 1550,
            "original_price": 2000,
            "currency": "BDT",
            "sizes": ["30", "32", "34", "36"],
            "colors": ["Army Green", "Black"],
            "stock": 30,
            "rating": 4.7,
            "image_url": "https://example.com",
            "description": "Multi-pocket durable cotton cargo pants for a rugged streetwear style."
        },
        {
            "id": 12,
            "name": "Graphic Print Casual T-Shirt",
            "category": "t-shirt",
            "price": 490,
            "original_price": 700,
            "currency": "BDT",
            "sizes": ["S", "M", "L", "XL"],
            "colors": ["White", "Yellow"],
            "stock": 150,
            "rating": 4.4,
            "image_url": "https://example.com",
            "description": "100% combed cotton t-shirt featuring high-quality durable screen print."
        },
        {
            "id": 13,
            "name": "Oxford Cotton Button-Down Shirt",
            "category": "shirt",
            "price": 1350,
            "original_price": 1700,
            "currency": "BDT",
            "sizes": ["S", "M", "L", "XL"],
            "colors": ["Light Pink", "Grey", "White"],
            "stock": 55,
            "rating": 4.5,
            "image_url": "https://example.com",
            "description": "Classic timeless Oxford weave shirt suitable for both office and casual wear."
        },
        {
            "id": 14,
            "name": "Pure Silk Luxury Panjabi",
            "category": "panjabi",
            "price": 5500,
            "original_price": 6500,
            "currency": "BDT",
            "sizes": ["40", "42", "44", "46"],
            "colors": ["Golden", "Off-White"],
            "stock": 10,
            "rating": 5.0,
            "image_url": "https://example.com",
            "description": "Exclusive pure silk panjabi with intricate hand embroidery for premium occasions."
        },
        {
            "id": 15,
            "name": "Formal Executive Trousers",
            "category": "pant",
            "price": 1650,
            "original_price": 2100,
            "currency": "BDT",
            "sizes": ["30", "32", "34", "36", "38"],
            "colors": ["Dark Grey", "Black", "Navy"],
            "stock": 40,
            "rating": 4.6,
            "image_url": "https://example.com",
            "description": "Premium wrinkle-free formal pants tailored for a sharp look."
        },
        {
            "id": 16,
            "name": "V-Neck Slim Fit T-Shirt",
            "category": "t-shirt",
            "price": 450,
            "original_price": 600,
            "currency": "BDT",
            "sizes": ["M", "L", "XL"],
            "colors": ["Charcoal", "Navy"],
            "stock": 90,
            "rating": 4.1,
            "image_url": "https://example.com",
            "description": "Lightweight stretchable cotton V-neck tee ideal for layering."
        },
        {
            "id": 17,
            "name": "Denim Casual Full Sleeve Shirt",
            "category": "shirt",
            "price": 1750,
            "original_price": 2200,
            "currency": "BDT",
            "sizes": ["M", "L", "XL"],
            "colors": ["Indigo", "Light Blue"],
            "stock": 28,
            "rating": 4.7,
            "image_url": "https://example.com",
            "description": "Rugged yet soft washed denim shirt with double front pockets."
        },
        {
            "id": 18,
            "name": "Slim Fit Athleisure Joggers",
            "category": "pant",
            "price": 990,
            "original_price": 1400,
            "currency": "BDT",
            "sizes": ["M", "L", "XL"],
            "colors": ["Black", "Melange Grey"],
            "stock": 75,
            "rating": 4.5,
            "image_url": "https://example.com",
            "description": "Comfortable Terry cotton track pants for gym, sports, or lounging."
        },
        {
            "id": 19,
            "name": "Striped Summer Polo Shirt",
            "category": "t-shirt",
            "price": 890,
            "original_price": 1200,
            "currency": "BDT",
            "sizes": ["S", "M", "L", "XL"],
            "colors": ["White-Blue Stripes", "Red-Black Stripes"],
            "stock": 65,
            "rating": 4.4,
            "image_url": "https://example.com",
            "description": "Yarn-dyed cotton striped polo shirt offering a sporty casual look."
        },
        {
            "id": 20,
            "name": "Casual Cotton Short Panjabi",
            "category": "panjabi",
            "price": 1500,
            "original_price": 1800,
            "currency": "BDT",
            "sizes": ["38", "40", "42"],
            "colors": ["Teal", "Mustard"],
            "stock": 33,
            "rating": 4.3,
            "image_url": "https://example.com",
            "description": "Trendy short-length panjabi crafted from breathable cotton for youth."
        }
    ]

};


module.exports = data;